import tkinter as tk
import threading
def networking()
def bind_widget(widg, party_name, party_var):
    def enter(event):
        widg.config(textvariable=party_name, fg="#393c4a", bg="#545766",)
    def leave(event):
        widg.config(textvariable=party_var, fg="#545766", bg="#393c4a",)
    widg.bind("<Enter>", enter)
    widg.bind("<Leave>", leave)
root = tk.Tk()
root.resizable(0,0)
root.geometry("914x155")
root.iconbitmap("wicon.ico")
root.title("WebWare (Live Poll Counter)")
party1 = tk.IntVar()
party1.set(0)
Party1 = tk.StringVar()
Party1.set("Party 1")
party2 = tk.IntVar()
party2.set(0)
Party2 = tk.StringVar()
Party2.set("Party 2")
party3 = tk.IntVar()
party3.set(0)
Party3 = tk.StringVar()
Party3.set("Party 3")
party4 = tk.IntVar()
party4.set(0)
Party4 = tk.StringVar()
Party4.set("Party 4")
f0nt = ("Times New Roman", 50)

p1 = tk.Label(root, textvariable=party1, fg="#545766", bg="#393c4a", font=f0nt, width=6, pady=37, relief=tk.RAISED)
p1.grid(row=0,column=0)
bind_widget(p1, Party1, party1)
p2 = tk.Label(root, textvariable=party2, fg="#545766", bg="#393c4a", font=f0nt, width=6, pady=37, relief=tk.RAISED)
p2.grid(row=0,column=1)
bind_widget(p2, Party2, party2)
p3 = tk.Label(root, textvariable=party3, fg="#545766", bg="#393c4a", font=f0nt, width=6, pady=37, relief=tk.RAISED)
p3.grid(row=0,column=2)
bind_widget(p3, Party3, party3)
p4 = tk.Label(root, textvariable=party4, fg="#545766", bg="#393c4a", font=f0nt, width=6, pady=37, relief=tk.RAISED)
p4.grid(row=0,column=3)
bind_widget(p4, Party4, party4)
root.mainloop()

